### ISSUE TITLE
Html native progress bar block the in-context editor

### ISSUE THREAD

**Issue by giardiv** [phrase/phrase-symfony2#3]
Using the in-context editor, the javascript transformation of the text doesn't work when introducing a HTML progress bar in the code

``` html
<h1>{{ 'dashboard.menu_bar.my_requests'|trans }}</h1>
<progress max="100" value="12"></progress> <span>12</span>
<h1>{{ 'dashboard.menu_bar.my_requests'|trans }}</h1>

<script>
    window.PHRASEAPP_CONFIG = {
        projectId: 'project_id'
    };
    (function() {
        var phraseapp = document.createElement('script'); phraseapp.type = 'text/javascript'; phraseapp.async = true;
        phraseapp.src = ['https://', 'phraseapp.com/assets/in-context-editor/2.0/app.js?', new Date().getTime()].join('');

        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(phraseapp, s);
    })();
</script>
```
**Nominal path**
![Without the progress bar](https://user-images.githubusercontent.com/8116383/37206210-015b50ee-2398-11e8-88ca-e2ecfb3929d3.png)
**When introducing the progress bar, the in-context editor disappear**
![With the progress bar](https://user-images.githubusercontent.com/8116383/37206293-59aa3be8-2398-11e8-8adb-b4cfb1d819dd.png)

* My application is running Symfony 3.4

**Comment by theSoenke** [comment]
Hi @giardiv, thanks for reporting it.  I will investigate what might cause this

**Comment by schwooz** [comment]
Hi @giardiv,

this is just a quick follow up to your bug report. We were able to fix that issue with the In-Context-Editor and released the fix recently.

Please get back to us, if the error still occurs.

Best wishes,
Michael
